import Head from "next/head";
import styles from "./index.module.css";
import { PostCard, PostWidget, CategoriesWidget } from "@/components";
import moment from "moment";

const DUMMY_POSTS = [
  {
    title: "React Testing",
    img: "/react-img.jpg",
    author: "Voyar",
    date: moment().format("MMM Do YYYY"),
    excerpt:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam fugiat laborum quos voluptas modi. Alias omnis facere voluptatibus tenetur quae?",
  },
  {
    title: "React Testing2",
    img: "/react-img.jpg",
    author: "Voyar",
    date: moment().format("MMM Do YYYY"),
    excerpt:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam fugiat laborum quos voluptas modi. Alias omnis facere voluptatibus tenetur quae?",
  },
  {
    title: "React Testing3",
    img: "/react-img.jpg",
    author: "Voyar",
    date: moment().format("MMM Do YYYY"),
    excerpt:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam fugiat laborum quos voluptas modi. Alias omnis facere voluptatibus tenetur quae?",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Next/Hygraph blog!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.main__layout} container`}>
        <div className={styles.main__layout__posts}>
          {DUMMY_POSTS.map((post) => {
            return <PostCard post={post} key={post.title} />;
          })}
        </div>
        <div className={styles.main__layout__sidebar}>
          <div className={styles.main__layout__sidebar__container}>
            <PostWidget posts={DUMMY_POSTS} />
            <CategoriesWidget />
          </div>
        </div>
      </div>
    </>
  );
}
